1619625241527 [Opening serial port: /dev/ttyTHS1.] 
1619625241828 [The robot is connected to ] [/dev/ttyTHS1] 
1619625241828 [Initial robot's topic...] 
1619625247889 [Data from: [w]] 
1619625252943 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 99, in handle_command
    time.sleep(1)
NameError: global name 'time' is not defined
] 
1619625252949 [Data from: [w]] 
1619625257982 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 99, in handle_command
    time.sleep(1)
NameError: global name 'time' is not defined
] 
1619625257988 [Data from: [w]] 
1619625263028 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 99, in handle_command
    time.sleep(1)
NameError: global name 'time' is not defined
] 
1619625263038 [Data from: [w]] 
1619625268078 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 99, in handle_command
    time.sleep(1)
NameError: global name 'time' is not defined
] 
1619625268085 [Data from: [w]] 
1619625273120 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 99, in handle_command
    time.sleep(1)
NameError: global name 'time' is not defined
] 
1619625273130 [Data from: [w]] 
1619625278166 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 99, in handle_command
    time.sleep(1)
NameError: global name 'time' is not defined
] 
1619625278170 [Data from: [w]] 
1619625283204 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 99, in handle_command
    time.sleep(1)
NameError: global name 'time' is not defined
] 
1619625283213 [Data from: [s]] 
1619625283214 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 105, in handle_command
    self.set_speed([-self._current_speed, -self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 101, in set_speed
    command += struct.pack("<H", speed)
error: ushort format requires 0 <= number <= USHRT_MAX
] 
1619625283214 [Data from: [ ]] 
1619625284424 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 92, in handle_command
    self.release_motor()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 206, in release_motor
    self.__robot_serial.set_stop()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 107, in set_stop
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 81, in write_command
    self.__robot_serial.write(command_send)
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 655, in write
    raise SerialException('write failed: {}'.format(e))
SerialException: write failed: [Errno 5] Input/output error
] 
1619625284429 [Data from: [ ]] 
1619625284433 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 92, in handle_command
    self.release_motor()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 206, in release_motor
    self.__robot_serial.set_stop()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 107, in set_stop
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 74, in write_command
    self.__robot_serial.write(command_send)
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 655, in write
    raise SerialException('write failed: {}'.format(e))
SerialException: write failed: [Errno 5] Input/output error
] 
1619625284441 [Data from: [ ]] 
1619625284445 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 92, in handle_command
    self.release_motor()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 206, in release_motor
    self.__robot_serial.set_stop()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 107, in set_stop
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 74, in write_command
    self.__robot_serial.write(command_send)
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 655, in write
    raise SerialException('write failed: {}'.format(e))
SerialException: write failed: [Errno 5] Input/output error
] 
1619625284449 [Data from: [ ]] 
1619625284453 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 92, in handle_command
    self.release_motor()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 206, in release_motor
    self.__robot_serial.set_stop()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 107, in set_stop
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 74, in write_command
    self.__robot_serial.write(command_send)
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 655, in write
    raise SerialException('write failed: {}'.format(e))
SerialException: write failed: [Errno 5] Input/output error
] 
1619625284458 [Data from: [ ]] 
1619625284463 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 92, in handle_command
    self.release_motor()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 206, in release_motor
    self.__robot_serial.set_stop()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 107, in set_stop
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 74, in write_command
    self.__robot_serial.write(command_send)
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 655, in write
    raise SerialException('write failed: {}'.format(e))
SerialException: write failed: [Errno 5] Input/output error
] 
1619625284468 [Data from: [ ]] 
1619625284473 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 92, in handle_command
    self.release_motor()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 206, in release_motor
    self.__robot_serial.set_stop()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 107, in set_stop
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 74, in write_command
    self.__robot_serial.write(command_send)
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 655, in write
    raise SerialException('write failed: {}'.format(e))
SerialException: write failed: [Errno 5] Input/output error
] 
1619625284478 [Data from: [ ]] 
1619625284486 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 92, in handle_command
    self.release_motor()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 206, in release_motor
    self.__robot_serial.set_stop()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 107, in set_stop
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 74, in write_command
    self.__robot_serial.write(command_send)
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 655, in write
    raise SerialException('write failed: {}'.format(e))
SerialException: write failed: [Errno 5] Input/output error
] 
1619625284499 [Data from: [ ]] 
1619625284507 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 92, in handle_command
    self.release_motor()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 206, in release_motor
    self.__robot_serial.set_stop()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 107, in set_stop
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 74, in write_command
    self.__robot_serial.write(command_send)
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 655, in write
    raise SerialException('write failed: {}'.format(e))
SerialException: write failed: [Errno 5] Input/output error
] 
1619625284520 [Data from: [ ]] 
1619625284525 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 92, in handle_command
    self.release_motor()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 206, in release_motor
    self.__robot_serial.set_stop()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 107, in set_stop
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 74, in write_command
    self.__robot_serial.write(command_send)
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 655, in write
    raise SerialException('write failed: {}'.format(e))
SerialException: write failed: [Errno 5] Input/output error
] 
1619625284531 [Data from: [ ]] 
1619625284536 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 92, in handle_command
    self.release_motor()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 206, in release_motor
    self.__robot_serial.set_stop()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 107, in set_stop
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 74, in write_command
    self.__robot_serial.write(command_send)
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 655, in write
    raise SerialException('write failed: {}'.format(e))
SerialException: write failed: [Errno 5] Input/output error
] 
1619625284543 [Data from: [ ]] 
1619625284550 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 92, in handle_command
    self.release_motor()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 206, in release_motor
    self.__robot_serial.set_stop()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 107, in set_stop
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 74, in write_command
    self.__robot_serial.write(command_send)
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 655, in write
    raise SerialException('write failed: {}'.format(e))
SerialException: write failed: [Errno 5] Input/output error
] 
1619625284560 [Data from: [ ]] 
1619625284568 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 92, in handle_command
    self.release_motor()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 206, in release_motor
    self.__robot_serial.set_stop()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 107, in set_stop
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 74, in write_command
    self.__robot_serial.write(command_send)
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 655, in write
    raise SerialException('write failed: {}'.format(e))
SerialException: write failed: [Errno 5] Input/output error
] 
1619625284573 [Data from: [ ]] 
1619625284579 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 92, in handle_command
    self.release_motor()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 206, in release_motor
    self.__robot_serial.set_stop()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 107, in set_stop
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 74, in write_command
    self.__robot_serial.write(command_send)
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 655, in write
    raise SerialException('write failed: {}'.format(e))
SerialException: write failed: [Errno 5] Input/output error
] 
1619625284585 [Data from: [ ]] 
1619625284590 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 92, in handle_command
    self.release_motor()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 206, in release_motor
    self.__robot_serial.set_stop()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 107, in set_stop
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 74, in write_command
    self.__robot_serial.write(command_send)
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 655, in write
    raise SerialException('write failed: {}'.format(e))
SerialException: write failed: [Errno 5] Input/output error
] 
1619625284598 [Data from: [w]] 
1619625284610 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 98, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 102, in set_speed
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 74, in write_command
    self.__robot_serial.write(command_send)
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 655, in write
    raise SerialException('write failed: {}'.format(e))
SerialException: write failed: [Errno 5] Input/output error
] 
1619625284615 [Data from: [w]] 
1619625284619 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 98, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 102, in set_speed
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 74, in write_command
    self.__robot_serial.write(command_send)
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 655, in write
    raise SerialException('write failed: {}'.format(e))
SerialException: write failed: [Errno 5] Input/output error
] 
1619625284624 [Data from: [w]] 
1619625284629 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 98, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 102, in set_speed
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 74, in write_command
    self.__robot_serial.write(command_send)
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 655, in write
    raise SerialException('write failed: {}'.format(e))
SerialException: write failed: [Errno 5] Input/output error
] 
1619625284648 [Data from: [w]] 
1619625284653 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 98, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 102, in set_speed
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 74, in write_command
    self.__robot_serial.write(command_send)
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 655, in write
    raise SerialException('write failed: {}'.format(e))
SerialException: write failed: [Errno 5] Input/output error
] 
1619625284657 [Data from: [w]] 
1619625284661 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 98, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 102, in set_speed
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 74, in write_command
    self.__robot_serial.write(command_send)
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 655, in write
    raise SerialException('write failed: {}'.format(e))
SerialException: write failed: [Errno 5] Input/output error
] 
1619625284665 [Data from: [w]] 
1619625284675 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 98, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 102, in set_speed
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 74, in write_command
    self.__robot_serial.write(command_send)
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 655, in write
    raise SerialException('write failed: {}'.format(e))
SerialException: write failed: [Errno 5] Input/output error
] 
